### ISSUE TITLE
Using 7.7.7 (@babel/core 7.7.7) required babel.config.json. 

### ISSUE THREAD

**Issue by spendres** [paralleldrive/riteway#243]
.babelrc no workie for me

Used the same contents from readme.md:
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": [
          "last 2 versions",
          "safari >= 7"
        ]
      }
    ],
    "@babel/preset-react"
  ]
}

**Comment by arshmakker** [comment]
@spendres 
could you share ur filestructure, where .bablerc is visible.

**Comment by spendres** [comment]
Not sure where I put the .babelrc file when it didn't work. I tried to
recreate the error but it turns out that either a babel.config.json or a
.babelrc file at the react project root works with the contents listed in
the readme.md:

{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": [
          "last 2 versions",
          "safari >= 7"
        ]
      }
    ],
    "@babel/preset-react"
  ]
}

**Comment by arshmakker** [comment]
@spendres 
Babel or most of theses kinds of tools, which support .**rc file, they need to have the config files at the root/top level of the project.

Hope it helps.

**Comment by spendres** [comment]
Yep. Works great!

**Comment by ericelliott** [comment]
Working with babel is documented.
