### ISSUE TITLE
riteway/esm/vitest is missing typescript type definition file.

### ISSUE THREAD

**Issue by krisnye** [paralleldrive/riteway#352]
<img width="1228" alt="Screenshot 2024-01-17 at 9 30 35 AM" src="https://github.com/paralleldrive/riteway/assets/783032/15202017-b28d-4b4e-bba9-569325e64e1c">

**Comment by ericelliott** [comment]
@krisnye @geireann Please coordinate a fix. 😄

**Comment by geireann** [comment]
Fix is included as part of #354
