### ISSUE TITLE
How to use RITEway with React Native?

### ISSUE THREAD

**Issue by janhesters** [paralleldrive/riteway#48]
Since React Native doesn't render HTML, I was wondering how one would use RITEway with React Native?

**Comment by ericelliott** [comment]
Hmmm... that's a good question. Maybe something that will just render to an object you can query, like [React test renderer?](https://medium.com/@pshrmn/testing-react-native-components-in-node-with-react-test-renderer-cb2985402dce)

**Comment by janhesters** [comment]
Interesting, that would work, but the React Test Renderer API looks tedious, especially for deep rendering.

I think there are 3 options:

1. Use React Test Renderer for the query and RITEway for the assertion.

2. I was thinking maybe you could combine RITEway with [React Native Testing Library](https://github.com/callstack/react-native-testing-library). It has a `getByType` method that lets you easily query and render. The downside is (as far as I know) you can only query for React Native's component types. If you use a library like React Native Elements for your UI components, you can't `getByType(ListItem)`, but have to search for `getByType(View)`.
Furthermore, RNTL comes with a bunch of other selectors that would fall more into the category of functional tests (which often require mocks) as you described in the docs.

3. Make a PR with to support `import render from 'riteway/render-react-native-component';` method here for RITEway.

What do you think?

I think 3. would be awesome.

**Comment by ericelliott** [comment]
I'm open to #3.

**Comment by janhesters** [comment]
@ericelliott Currently working on a PR 😊 Unfortunately, I can't get RN components to run in the tests 😢 It always complains: 

```bash
UnhandledPromiseRejectionWarning: Error: Cannot find module 'View'
```

I assume it has something to do with babel and tape, but I couldn't figure out what is wrong. 

I added the preset `metro-react-native-babel-preset` but this just led to the error:

```bash
> node -r babel-register -r babel-polyfill source/test
/path/to/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328
        throw e;
        ^

Error: Couldn't find preset "module:metro-react-native-babel-preset" relative to directory
```

Please et me know if you have an idea what could be wrong. Either way, I will keep trying to find a solution.

**Comment by janhesters** [comment]
So I wanted to give a little update on this issue / the PR I was working on.

I got the following code for RITEway working:

```js
// source/render-rn-component.js
import TestRenderer from 'react-test-renderer';

export class ErrorWithStack extends Error {
  constructor(message, callsite) {
    super(message);
    if (Error.captureStackTrace) {
      Error.captureStackTrace(this, callsite);
    }
  }
}

const prepareErrorMessage = error =>
  // Strip info about custom predicate
  error.message.replace(/ matching custom predicate[^]*/gm, '');

const render = component => TestRenderer.create(component).root;

const getByTestId = instance => (testID = '') => {
  try {
    return instance.findByProps({ testID });
  } catch (error) {
    const preparedError = new ErrorWithStack(prepareErrorMessage(error));
    if (preparedError.message.includes('No instances found')) {
      return null;
    }
    throw new ErrorWithStack(preparedError.message, getByTestId);
  }
};

const getAllByTestId = instance => (testID = '') => {
  try {
    return instance.findAllByProps({ testID });
  } catch (error) {
    return [];
  }
};

const findByTestId = component => getByTestId(render(component));
const findAllByTestId = component => getAllByTestId(render(component));

export default render;
export { findByTestId, findAllByTestId };
```

With these functions the code can be used like this:

```js
// source/test.js
describe('renderRNCompenent', async assert => {
  const text = 'Foo';
  const component = renderRN(
    <View>
      <Text>{text}</Text>
    </View>
  );

  assert({
    given: 'A React Native component',
    should: 'return a working react test renderer instance',
    actual: component.findByType('Text').props.children,
    expected: text,
  });
});

describe('getByTestId', async assert => {
  const text = 'Foo';
  const $ = getByTestId(
    <View>
      <Text testID='foo'>{text}</Text>
    </View>
  );

  assert({
    given: 'A React Native component',
    should: 'return a working react test renderer instance',
    actual: $('foo').props.children,
    expected: text,
  });
});
```

I know this code works because I tested it with Jest. But the problem of my issue earlier still persists.

Basically Jest is the only library right now that has working mocks of the React Native tags (`<View />`, `<Text />` etc.). [There is an old public mock ](https://github.com/RealOrangeOne/react-native-mock) but the repository is no longer maintained. And even the code of the PR's is outdated.

At this point one would have to:

1. Either give RITEway it's own mocking capabilities, or find a good mocking library that RITEway would then have to depend on.
2. Mock out React Native completely.

Unfortunately I have no idea how long that would take, let alone where to start when trying to mock out RN.

At this point I think there are 3 options:

1. Say f*** it and leave RN to be tested with Jest and unRITE assertions.
2. Find someone who has the time and skills to mock out RN.
3. Migrate RITEway to use jest instead of tape.

Option 3. is probably the least amount of effort and has the benefit of having the FB Jest team maintain the RN mock. I just don't know whether Jest's output can be modified so that it prints out TAP like output. You could definitely write a wrapper around it Jest's `it` and `test` so that you could use 

```js
assert({
  given: 'something',
  should: 'return that',
  actual: fn(something),
  expected: that,
});
```

**Comment by janhesters** [comment]
Update: I wrote a wrapper so one can use the RITEway API with Jest :) You can check it out here: [RITEway-Jest](https://github.com/janhesters/riteway-jest).
